    <?php include("../header.inc.php"); ?>
    <div id="subHeader"> <!-- For easy determination of current page, without the nasty PHP/JS -->
      Character and Personal Bios
    </div>
    <div id="bioContent"> <!-- Start Index Content -->
      <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur a tellus eu ipsum accumsan dapibus. Nunc quis tortor. Sed fermentum. Nam nisl velit, porta ut, aliquet quis, accumsan non, ligula. Proin ultricies, pede ut pretium commodo, eros nulla posuere est, vitae pharetra felis felis vel magna. Sed sit amet erat. Vivamus vestibulum tristique sapien. Quisque eros orci, pharetra sit amet, mollis ac, ultrices a, odio. Nullam elementum faucibus purus. Ut tellus lectus, adipiscing vitae, tempus et, feugiat eget, est. Praesent risus est, pretium scelerisque, elementum in, lacinia sit amet, orci. Mauris et metus sit amet odio tempor iaculis. Nam felis. In tristique aliquam elit. Nunc in nibh. Curabitur est. Praesent interdum, lectus lobortis tempor accumsan, quam est vulputate diam, imperdiet viverra nibh augue ac arcu. Etiam nisi.</p>
      <p>Integer in ante. Mauris turpis nisl, ullamcorper ac, ultrices a, semper et, ipsum. Maecenas et augue. Mauris tincidunt pede. Aenean arcu. Pellentesque quis urna. Fusce et ligula. Ut placerat elementum quam. Fusce eu ligula. Donec eget erat a quam fermentum sodales. Phasellus quis lorem ut nisi congue vehicula. Proin ultricies quam vel eros. Nulla facilisi.</p>
      <p>Aliquam ornare, ligula sed volutpat placerat, nulla nisl tempor arcu, sit amet ullamcorper sapien odio ac nisi. Donec vitae ante at justo vulputate condimentum. Nam pede enim, pulvinar ut, adipiscing ac, cursus eget, lectus. Suspendisse porttitor facilisis arcu. Fusce consequat vehicula neque. Nam in mauris non nulla consectetuer nonummy. Nunc lectus turpis, posuere et, tincidunt sit amet, elementum nec, libero. Suspendisse mattis accumsan nulla. In eget magna vel lorem dictum consectetuer. Quisque a justo. Fusce eget ipsum.</p>
      <p>Suspendisse hendrerit lacus id lectus. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Cras vehicula egestas nisl. Suspendisse ipsum enim, molestie quis, aliquet vitae, rutrum a, lorem. Morbi molestie. Pellentesque vestibulum aliquam eros. Pellentesque in mauris. Donec bibendum, tellus a varius rhoncus, nisi lorem tincidunt nisl, vel egestas turpis nisi non risus. Vivamus quis nibh. Vestibulum eget sapien. Cras ut augue a augue placerat tempor. Aenean congue eleifend nulla. Vivamus leo leo, dictum vel, scelerisque eu, hendrerit vel, est. Suspendisse pede elit, sodales non, ultrices vitae, ullamcorper ac, mi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin quis arcu sit amet sem hendrerit molestie.</p>
      <p>Ut porta, purus fermentum euismod ultricies, erat felis commodo enim, vitae convallis mi quam semper risus. Maecenas imperdiet, velit eget malesuada commodo, neque lectus posuere libero, laoreet posuere mauris felis non lorem. Fusce felis nunc, pharetra ac, porttitor sed, malesuada eu, quam. Donec eros nulla, sagittis id, commodo id, viverra ut, nisi. Nam blandit ligula a nunc. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Vestibulum non augue id orci vestibulum facilisis. In hac habitasse platea dictumst. Nullam gravida purus a augue. Nam viverra dui eget tortor. Morbi porttitor mi in ante. Praesent sed nunc sodales odio vulputate tempor. Suspendisse eu nunc. Maecenas vestibulum sapien nec metus. Aliquam at erat. Nullam neque nulla, cursus nec, dictum quis, pretium sit amet, lorem. Duis purus felis, viverra ut, molestie non, convallis faucibus, odio. Fusce bibendum nulla a risus. Aenean non leo sit amet nulla adipiscing pharetra.</p>
    </div> <!-- End Index Content -->
    <?php include("../footer.inc.php"); ?>
