		<?php include('includes/header.php'); ?>
		
		<section id="home" class="content">
		
			<?php include('includes/links.php'); ?>

			<p>Cold Candor, my home away from home.	 Obviously, this site isn't much to look at at the moment, but I have big plans for it.	 I just need a good design scheme to use and an idea of exactly what I want to use this site for, and the time to make it happen...</p>
			<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas quis metus nec felis mollis tincidunt. Donec adipiscing orci vel urna. In placerat lacus ac est. Maecenas nec orci a tellus aliquam condimentum. In hac habitasse platea dictumst. Suspendisse consectetuer, nulla non sollicitudin vulputate, ante urna faucibus elit, et mollis leo eros non nulla. Etiam sodales. Integer pulvinar. Nunc quis erat at eros ullamcorper tempus. Mauris aliquet. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam urna elit, lacinia in, semper in, lobortis at, lorem.</p>
			<p>Vivamus vestibulum consectetuer mauris. Praesent suscipit leo id enim. Praesent varius blandit felis. Sed vitae dui. Integer id velit at lectus cursus fermentum. Pellentesque egestas accumsan arcu. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Pellentesque a arcu. Nam ut sapien non massa auctor pulvinar. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur pellentesque. Vivamus erat libero, pulvinar vitae, sodales quis, rhoncus et, velit. Nullam eget felis. Sed id elit. Vestibulum tincidunt.</p>
			<p>Phasellus sit amet lectus et justo aliquet feugiat. Quisque facilisis risus id lacus. Donec ac nibh et elit hendrerit tempor. Curabitur facilisis turpis non metus. Donec eu orci non augue auctor faucibus. Morbi placerat, lectus id lobortis elementum, mi dui dictum nulla, ac dignissim arcu diam ut odio. Etiam a leo. Ut ultricies sapien. Aliquam varius mi id risus. Nulla facilisi.</p>
			<p>Quisque pede augue, laoreet eget, pulvinar et, ultricies ac, dui. Nam vel neque ac sapien egestas sodales. In bibendum nunc quis enim. Nullam ac ante nec enim posuere lobortis. Nullam vitae mi dignissim arcu tempus cursus. Integer ipsum lacus, lobortis vel, pellentesque vel, pretium nec, nisl. Nunc at urna in dui auctor convallis. Sed ligula mauris, bibendum sed, consequat non, viverra eu, mi. Etiam lacinia tortor ut pede accumsan eleifend. Etiam orci.</p>
			<p>Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Proin hendrerit. Vivamus augue urna, vulputate in, fermentum a, euismod vel, enim. Ut imperdiet, turpis id vulputate condimentum, elit nisi vestibulum diam, quis adipiscing augue arcu ac turpis. Donec ac ligula. Suspendisse blandit. Nunc justo. Morbi bibendum ultricies erat. Nulla vel metus vitae nibh condimentum aliquam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut leo. Sed et magna. Nulla facilisi. Donec imperdiet, elit a feugiat tempor, nibh est blandit eros, ut egestas augue lectus et eros. Vestibulum tempor neque et felis. Nunc vel lorem a sem sollicitudin rutrum. Praesent vitae eros. Praesent sodales, dui eget dignissim aliquet, mauris nisl laoreet leo, eu bibendum purus lectus sed tellus. Sed at magna. Fusce adipiscing.</p>

		</section>

		<?php include('includes/footer.php'); ?>