    <?php include("../header.inc.php") ?>
    <div id="subHeader"> <!-- For easy determination of current page, without the nasty PHP/JS -->
      The Guild Charter
    </div>
    <div id="charterContent"> <!-- Start Index Content -->
      <p>What follows are the Rules and Guidelines for being a member of Freedom's Choice.</p>
      <p>The members of this Guild hold true to the values of loyalty, honor, and intelligence in gameplay. Yes, this is a game we're playing, and it is supposed to be fun for everyone. As such, and since it appears that these guidelines need to be written down, here is our basic charter and explanation of rules.</p>
      <h3>1 - General Code of Conduct</h3>
      <p>We designed this guild as a place where a group of friends could get together and play WOW to its fullest enjoyment. We wanted to make sure help was there if a member was stuck in a certain quest or needed help or advice.</p>
      <h4>Section A - Trade</h4>
      <p>As the guild grew, more and more options became available to us. Members became high level enchanters, blacksmiths, leatherworkers, tailors, and the like. Now it became possible to craft new and better items for other members of the guild, allowing us to outfit our little group that much better. This was a great idea, and it caught on fast. Here are some rules concerning inter-guild trade:</p>
      <ol>
        <li>We have high level proffessions now - Use them :) Find out what each member can do, and if they can help you out with an armor piece or whatnot, ask, and ask nicely.</li>
        <li>Unless the aforementioned tradesman specifically says that he will make something for you as a gift, make sure you compensate him for his work. Bring him the materials needed to craft whatever it is you're having him make (If you don't know what materials are needed, ask him).</li>
        <li>Because we're growing, and regulating who is invited into the guild is hard to do, NEVER give someone that you just met money or items or materials. Guild members do NOT ask for money from other guild members. If you're 5 gold short and ready to get your mount, contact the GM and talk to him. The officers in the Guild are nice people, honest!</li>
      </ol>
      <h4>Section B - Helping Members</h4>
      <p>Helping members of the Guild is what we're founded on. It is highly encouraged, and can be very enjoyable too. However, sometimes this can be abused. To prevent this from happening, and to make sure everyone has an enjoyable experience, here are some guidelines for helping in the Guild.</p>
      <ol>
        <li>If you need help, ask.</li>
        <li>Try to take a bit of time to help the lower-level members. The higher they level, the better for the guild as a whole. We do want to do Raids and End-Game stuff eventually.</li>
        <li>Do NOT request help with something you shouldn't be doing anyway. No sixty in the guild is going to take time out of his day to escort a level 10 through The Burning Steppes. We will help you run instances that you have quests for. We will help with elite quests that you just can't seem to finish on your own. Mostly, we help with quests. Keep that in mind when asking for help.</li>
      </ol>
      <h4>Section C - Interacting with Guildies</h4>
      <p>This section is a nessesary evil. So I will make it quick and painless.</p>
      <ol>
        <li><strong>Watch the language.</strong> Most of us are mature (mostly) adults. We can handle the random F-bomb, or the exclamation of "HOLY SHIT! AN EPIC JUST DROPPED!" What we do NOT want to see are racial slurs, verbal attacks on other members of the guild, or talk that you wouldn't be comfortable saying around your Mom.</li>
        <li><strong>Don't be stupid.</strong> Please. Yes, we joke around a lot, but don't spam us with unintelligible garbage. It's annoying, and there are at least two English majors who will call you on it. We don't mind typos (the GM is dyslexic when typing), and you don't have to use proper grammar all the time either. But this: "wut r u 2 doing? ya that ROXORs my BOXORS" or "F34r m3, and my l33t ski11z!" will send most people into fits of murderous rage.</li>
      </ol>
      <p>All that being said, just be yourself, and don't feel you have to be "cool" or "funny" to fit in here. We're all playing WOW in our spare time. I don't think any of us are really concerned with being "cool."</p>
      <h3>2 - Rules for Groups (Instances and General Group Play)</h3>
      <p>Here we go, these rules will help you in ANY group that you're in.</p>
      <ol>
        <li><strong>Items</strong> - When an item drops in a group, you have three choices: Need, Greed, or Pass. If there is an item that drops and it is better than what you have on you, ask the other members of the group if it is okay for you to "Need" that item. For most other items, Greed is an okay choice. If an Item drops that is BoP or Bind on Pickup, PASS. If you really need it, and are planning on using it, ask if you can roll for it. If nobody in the group can use it and there is an enchanter in the group, Pass, and then let the enchanter disenchant the item. Then you can all roll for whatever the item disenchanted into. If, by the grace of the WOW gods, an Epic drops, PASS. This is a different sort of dilema. The general Rule is that everyone in the group will roll on it, and the winner of the roll takes the Epic. A good thing to keep in mind when in a group, is to just ask if you can do something. People like that a lot better than you just doing whatever and possibly making the people in your group very angry.</li>
        <li><strong>Ninjas</strong> - Don't do it! That's final. What's a ninja? A ninja is someone who loots things while other members of the group are still fighting. They roll "need" when they don't really need it, and they never ask. DO NOT BE A NINJA. As an example of what NOT to do here is a bit about a FORMER member: Four of our guildies got in a group with a priest from another guild to do LBRS (big instance). An Epic dropped, and like you're supposed to, everyone passed. Then there was a roll to see who would get it. The priest won, but this former member had said he wanted it real bad. The priest offered to sell him the weapon for 100 gold (not a bad price actually). Well this FORMER member raced over to the body, picked up the epic and equipped it before the priest had a chance to pick up what was rightfully his. That member was immediately kicked from the guild (and good riddance) and the three remaining guildies pooled together their money and paid the priest for the weapon. I think they actually gave him more than 100 gold to keep relations pleasant. In the end the priest considers us a stand-up guild and we are on good terms. What this FORMER member did was a prime example of a ninja, and it will not, under any circumstances, be tolerated here.</li>
        <li><strong>Strategies</strong> - If you've never been in an instance before, it's a good idea to let someone who has take the lead. Listen to the plans, contribute what you can, and do your best to follow them. Nobody wants to wipe. Play together and work as a team, and any instance is do-able.</li>
        <li><strong>Tanks</strong> - What is a tank? Simply put, a tank is someone who soaks up damage and deals it back. In a group, the tank is your foward man/woman. It is their job to be the meatshield. They try their hardest to hold the aggro of every baddie in the area so that all the enemies are hitting the tank and nobody else. This is their job. They take the damage so the other players don't have to. Ideally, a protection warrior is who you want for your tank. I have seen the job done by other types as well, however. Paladins can tank fairly well, and I have seen other classes perform these duties as well.</li>
        <li><strong>Off-tanks</strong> - This is your back-up tank. In case your Tank dies, it is good to have a back-up. Most often this role is played by a Paladin.</li>
        <li><strong>Healer</strong> - This is idealy a role for priests and resto-druids. It is their job to keep the Tank alive at all costs. They can also keep an eye on the other members of the group, but if the tank dies, it's bad news for everyone.</li>
        <li><strong>Off-healer</strong> - This is a good job for pallies. In this role you keep an eye on everyone else in the group, healing as needed, especially the priest.</li>
        <li><strong>DPS (Damage Per Second)</strong> - These are your damage-dealing, killing machines. Some classes that fit this role well are Rogue, Hunters, Mages, and Warlocks. The job here is simple. You kill things. Generally, if the focus is killing a boss, you wait for your tank to get the aggro, then you go in and hack and slash and blast away.</li>
        <li><strong>Sheep, Sap, Chain, and Banish</strong> - Rouges have the ability to Sap baddies (Mostly just Humanoids - No Undead). This stuns the enemy for 60 seconds. They will remain unmoving and effectively out of the fight until the 60 seconds is over or someone hits them. The sap has to come first since you can NOT sap someone in battle. Mages can Sheep people. This turns the enemy into a sheep and the enemy will remain as a sheep until they are hit or the spell wears off. Mages can do this at any time in the fight so if your enemy suddenly turns into a sheep, do NOT hit them. Priests can Chain enemies, making them immobile much like the sap. Again, do not hit the enemy that is chained. Warlocks can Banish demons and elementals. This both takes the enemy out of the fight and makes them invulnerable while banished. Don't hit them, you're wasting time. In a good group, the leader will assign targets to be immoblized so that you can pick a group of baddies apart one by one.</li>
        <li><strong>Kite</strong> - What does it mean to "Kite" something. In the case of major baddies with friends, sometimes a good plan is to have someone "kite" one of the baddies while the rest of the group deals with just one of them. Basically, if you are doing the "Kite-ing", you grab the attention of a baddie and run. You keep his focus on you and play bait while your friends kill the other one. You get him as far away from your friends as you can, and try to survive until they've killed the other baddie. This job usually ends up as a sacrifice play. But that's okay. If you end up dying, but your friends were successful in defeating their baddie, now they only have one to deal with and will be more likely to succeed. Dying to ensure victory isn't a bad thing. They'll rez you and all will be well. (As a side note, this job is NOT good for a rezzer. Rezzers need to be kept alive.)</li>
      </ol>
      <h3>3 - Conclusion (Finally)</h3>
      <p>We all want to have FUN! This is, after all, a game! So have fun, play nice with others, and just be smart about it. We're a pretty laid back guild, but we're loyal to the core. A lot of us are friends in Real Life as well as in WoW. In other words, welcome to the family!</p>
      <p>~Trenith Kaos - Colonel</p>
    </div> <!-- End Index Content -->
    <?php include("../footer.inc.php") ?>
