    <?php include("../header.inc.php"); ?>
    <div id="subHeader"> <!-- For easy determination of current page, without the nasty PHP/JS -->
      Guild History
    </div>
    <div id="historyContent"> <!-- Start Index Content -->
      <p>This guild has been around for a long time, more or less since the inception of the game. The original founding GM was Sev. None of the other founding members stayed long, but Sev held on with a desire to form a guild of friends that loved to play together. After a time, a core of people developed, consisting of Arch, Runa, Tren, Con, Slake, Gabe, Mel, Who, Rah, Red, Mija, Mijito, and a few others, most of which were friends in Real Life. The current GM, Ham, joined while this core was still the majority of the guild, around 7 months before The Burning Crusade.</p>
      <p>Slowly but surely, we grew powerful enough to start assaulting the level 60 instances like Strat and Scholo, often having exactly 5 levels 60's available at all. It stayed this way for a time, growing very slowly, until shortly before the expansion was released, we ran our first almost-entirely (brought in 1 external player) guild UBRS run. Downing the entire zone on the first attempt, this was a huge achievement for our small guild, and a ton of fun for all involved too!</p>
      <p>While I measure our growth in instances, we were also growing in our core and our general size. Shortly after the expansion, there was a boom in membership. No one is quite sure what caused it, but in the course of a couple months we grew from around 90 members, including alts and banks, to 320 members! We were happy to have them, but it invariably lead to conflict and hard feelings, and eventually to a change in leadership from Arch and Runa to Ham and Who.</p>
      <p>We had people join from everywhere... A merger with a guild that was going under, called Blood-Stained Hands, people leaving high-end raiding guilds like Excusia and Seraph, people inviting RL friends and family. We have entire families in the guild now, many couples, kids as young as 8 or 9, and folks so old you don't ask how old they are :P It's all one big family.</p>
      <p>With the population boom also came talk of real end-game progression. So, attempting to maintain the environment the guild was made to be, we began raiding ZG and AQ20 to get a feel for large-group dynamics, and to have fun kicking the crap out of the old-world bosses :P We recently started Karazhan, but with more people available then positions available, especially with our general lack of healers and tanks and large amount of DPS, tempers grew hot and conflict arose. This lead to a guild falling-out that threatened to split us. Harsh words were said and the leadership was passed on, but we prevailed.</p>
      <p>We now have a strong core of officers, lots of talent, and many many interesting people. We have people that just love to go explore the world and hang out with friends. We have hard core raiders and PvPers. We have Casual players that are willing to go with whatever's happening at the time. As such, we feel we have something to offer everyone.</p>
    </div> <!-- End Index Content -->
    <?php include("../footer.inc.php"); ?>
